[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["dependencies"]
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
fuzz = { runs = 1024 }
invariant = { runs = 256, depth = 64 }

[profile.ci]
fuzz = { runs = 10000 }

[rpc_endpoints]
amoy = "${AMOY_RPC_URL}"

[etherscan]
amoy = { key = "${POLYGONSCAN_API_KEY}", chain = 80002 }

[fmt]
line_length = 110
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
